import 'package:isar/isar.dart';
import 'package:flutter/material.dart';

part 'theme_preference.g.dart'; // This will be generated by isar_generator

@collection
class ThemePreference {
  Id id = Isar.autoIncrement; // Primary key, auto-incremented

  @enumerated
  ThemeMode themeMode; // Store ThemeMode as an enum

  ThemePreference({required this.themeMode});
}
